# [Настройка пластинок]

# Расстояние (в блоках), с которого пластинки могут быть услышаны.
music-disc-distance: 16

# Основная громкость музыкальных дисков от 0 до 1. (Вы можете установить такие значения, как 0,5 для 50% громкости).
music-disc-volume: 1